#!/bin/sh

echo "Installing Tanlinell"

rm -rf .git*            && \
rm README.md            && \
cd hybrid-core          && \
rm -rf .git*	        && \
cd ../           		&& \
rm init

echo "Tanlinell successfully installed"